backend:
  name: github
  repo: Andrex501/saqua
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "contenido"
    label: "Contenido"
    files:
      - name: "actividades"
        label: "Actividades"
        file: "data/actividades.json"
        fields:
          - label: "Listado de actividades"
            name: "items"
            widget: "list"
            allow_add: true
            summary: "{{fields.titulo}} — {{fields.fecha}}"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Texto", name: "texto", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }
              - { label: "Fecha", name: "fecha", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
